version: "3.8"

services:
  # Serviço do MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Serviço da aplicação Node.js
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    environment:
      - MONGO_URI=${MONGO_URI}
      - NODE_ENV=${NODE_ENV}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
    command: "npx nodemon src/index.ts"
    stdin_open: true
    tty: true

volumes:
  mongo_data:

